### ISSUE TITLE
Consider adding warning when limits are out of bounds

### ISSUE THREAD

**Issue by jacobq** [dresende/node-modbus-tcp#24]
As noted on [the Wikipedia article](https://en.wikipedia.org/wiki/Modbus#Function_code_4_.28read_input_registers.29_and_function_code_3_.28read_holding_registers.29), Modbus TCP is limited to transferring up to 127 16-bit registers at once. Currently, if one attempts to `client.readHoldingRegisters(unitId, from, to, ...)` where `to - from > 127` bad things can silently happen. The slave device I was using sent me a response whose size has wrapped around the max of the field, so instead of getting 192 registers I got 64.

Have you considered adding an initialization option that causes a bounds check to take place when the function is called, and then having it fire the callback with an error if the size limit is exceeded?

**Comment by jacobq** [comment]
In case it's helpful to anyone else, here is some code I wrote to split large requests into chunks and reassemble:


```
class ModbusClient {
    constructor(unitId) {
        this.unitId = (typeof unitId === 'undefined') ? 1 : unitId;
    }

    connect(conn) {
        this.conn = conn;
        this.client = new modbus.Client();
        this.client.pipe(conn);
    }
    // ... 
    readHoldingRegisters(from, to, unitId) {
        //console.log('[DEBUG] readHoldingRegisters', from, to, unitId);
        if (typeof unitId === 'undefined')
            unitId = this.unitId;

        const maxSize = 127;
        // If size is too large for single message, split into chunks and reassemble
        const numberOfChunks = Math.ceil((to - from + 1) / maxSize);
        let promises = [];
        for (let i=0; i < numberOfChunks; i++) {
            let chunkStart = from + i*maxSize;
            let chunkEnd = Math.min(to, chunkStart + maxSize - 1);
            //console.log('[DEBUG] chunking:', chunkStart, chunkEnd);
            const promise = new Promise((resolve, reject) => {
                this.client.readHoldingRegisters(unitId, chunkStart, chunkEnd, (err, regs) => {
                    if (err)
                        reject(err);
                    else
                        resolve(regs);
                });
            });
            promises.push(promise);
        }
        return Promise.all(promises).then(chunks => {
            //console.log('[DEBUG] reassembling chunks', chunks);
            return Array.prototype.concat(...chunks);
        });
    }
    // ... 
```

**Comment by dresende** [comment]
I try to follow the specification but avoid being pedantic about some restrictions. The TCP transport has no limit (the layer below) as it should split the packet if it's large enough. The TCP header (MBAP) has a 2 bytes for length which should give enough to request well above 127 records. The problem here is specific to some function codes, like the first 4 which replies with 1 byte saying `the number of bytes to follow`. The first 2 don't have the limit so low because they're bits so you can request 2K of coils.

I'm not using this module anymore, I'm maintaining [pdu](https://github.com/node-modbus/pdu) and [stream](https://github.com/node-modbus/stream). I think this should be solved in the PDU module, throwing errors when users try to create packages with over the limit values.

**Comment by jacobq** [comment]
Gotcha -- I'll checkout stream+pdu later. Thanks.
